gpu: null # "0"
multi_gpu:  "0,1,2,3,4"

model: TFlow

full: True
rm_history: True
eval: False

last_relu: False
allow_less_points: False

# general args
batch_size: 50
epochs: 600
lr: 0.001
seed: 1234

use_sgd: False
optimizer: Adam
pretrained: False
weight_decay: 0.0001
decay_steps: 800000
decay_rate: 0.7

dim: 3
num_points: 2048
repeat_num: 1

DEVICE: cuda

evaluate: False

dataset: Carla3D 
data_root: /dataset/public_dataset_nas/flownet3d/data_processed_maxcut_35_20k_2k_8192/

model_dir: checkpoints/
model_path: ''
exp_name: Flow_FLowNet3D_FT3D_2023_v4 # Test #T

data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True

# data augmentation
aug_together:
  degree_range: 0.1745329252
  shift_range: 1.
  scale_low: 0.95
  scale_high: 1.05
  jitter_sigma: 0.01
  jitter_clip: 0.00

aug_pc2:
  degree_range: 0.
  shift_range: 0.3
  jitter_sigma: 0.01
  jitter_clip: 0.00

# miscalleneous
workers: 12

is_training: True

